//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;


    public partial class Game
    {
        public int GameID { get; set; }
        public string Winner { get; set; }
        public Nullable<int> Moves { get; set; }
    }


